# Generated by Django 5.2.1 on 2025-08-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("calories", models.FloatField(help_text="Калории на 100 г")),
                ("protein", models.FloatField(help_text="Белки (на 100 г)")),
                ("fat", models.FloatField(help_text="Жиры (на 100 г)")),
                ("carbs", models.FloatField(help_text="Углеводы (на 100 г)")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
