# Generated by Django 5.2.5 on 2025-11-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nutrition", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["category", "name"],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("meat", "Мясо и птица"),
                    ("fish", "Рыба и морепродукты"),
                    ("dairy", "Молочные продукты"),
                    ("eggs", "Яйца"),
                    ("cereals", "Крупы и злаки"),
                    ("bread", "Хлеб и выпечка"),
                    ("vegetables", "Овощи"),
                    ("fruits", "Фрукты"),
                    ("nuts", "Орехи и семена"),
                    ("oils", "Масла и жиры"),
                    ("legumes", "Бобовые"),
                    ("sweets", "Сладости"),
                    ("beverages", "Напитки"),
                    ("other", "Другое"),
                ],
                default="other",
                help_text="Категория продукта",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="fiber",
            field=models.FloatField(default=0, help_text="Клетчатка (на 100 г)"),
        ),
    ]
